default linux
prompt 0
timeout 10

label linux
	linux /Image
	fdt /rk3588-rock-5b.dtb
	append root=/dev/mmcblk1p2 earlycon=uart8250,mmio32,0xfeb50000 console=ttyFIQ0,1500000n8 consoleblank=0 rootwait quiet cgroup_no_v1=all
